export const orderBy = [
  { id: 0, value: 'score' },
  { id: 1, value: 'popularity' },
  { id: 2, value: 'rank' },
  { id: 3, value: 'scored_by' },
  { id: 4, value: 'favorites' },
  { id: 5, value: 'members' },
  { id: 6, value: 'mal_id' },
  { id: 7, value: 'title' },
  { id: 8, value: 'type' },
  { id: 9, value: 'rating' },
  { id: 10, value: 'episodes' },
  { id: 11, value: 'start_date' },
  { id: 12, value: 'end_date' },
];