//Типы селектов
export enum DropdownTypeEnum {
  GENRES = 'genres',
  TYPES = 'types',
  SORT = 'sort',
  RATING = 'rating',
  SEASON = 'season',
  EPISODE = 'episode',
  PRODUCER = 'producer',
  STATUS = 'status',
  ORDER = 'order',
}

//Названия жанров
export const genresNamesData = [
  'Action',
  'Adventure',
  'Avant Garde',
  'Comedy',
  'Drama',
  'Fantasy',
  'Horror',
  'Isekai',
  'Mystery',
  'Romance',
  'Sci-fi',
  'Slice of Life',
  'Sports',
  'Supernatural',
  'Suspense',
  'Josei',
  'Kids',
  'Seinen',
  'Shoujo',
  'Shounen',
  'Boys Love',
  'Girls Love',
  'Adult Cast',
  'Anthropomorphic',
  'CGDCT',
  'Childcare',
  'Combat Sports',
  'Detective',
  'Educational',
  'Gag Humor',
  'Gore',
  'Harem',
  'High Stakes Game',
  'Historical',
  'Love Polygon',
  'Idols (Female)',
  'Mythology',
  'Parody',
  'Psychological',
  'Racing',
  'Reverse Harem',
  'School',
  'Space',
  'Time Travel',
  'Vampire',
  'Video Game',
  'Ecchi',
  'Erotica',
  'Hentai',
  'Gourmet',
  'Workplace',
  'Visual Arts',
  'Survival',
  'Super Power',
  'Team Sports',
  'Showbiz',
  'Samurai',
  'Strategy Game',
  'Reincarnation',
  'Romantic Subtext',
  'Pets',
  'Performing Arts',
  'Otaku Culture',
  'Music',
  'Military',
  'Medical',
  'Mecha',
  'Martial arts',
  'Organized Crime',
  'Mahou Shoujo',
  'Magical Sex Shift',
  'Iyashikei',
  'Idols (Male)',
  'Award Winning',
  'Crossdressing',
  'Delinquents',
];
//Название типов
export const AnimeTypesData = [
{id: 0, value: 'tv'},
{id: 1, value: 'movie'},
{id: 2, value: 'ova' },
{id: 3, value: 'special'},
{id: 4, value: 'ona'},
{id: 5, value: 'music'}]
//Название рейтингов
export const AnimeRatingData = [
  {id: 0, value: 'G - All Ages',},
  {id: 1, value: 'PG - Children',},
  {id: 2, value: 'PG-13 - Teens 13 or older',},
  {id: 3, value: 'R - 17+ (violence & profanity)',},
  {id: 4, value: 'R+ - Mild Nudity',},
  {id: 5, value: 'Rx - Hentai',},
];

export enum AnimeRatingQuery {
  'G - All Ages' = 'g',
  'PG - Children' = 'pg',
  'PG-13 - Teens 13 or older' = 'pg13',
  'R - 17+' = 'r17',
  'R+ - Mild Nudity' = 'r',
  'Rx - Hentai' = 'rx',
}
